### ISSUE TITLE
Add @ibnesayeed's negative space logo

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/logo#1]
Ahem, @ibnesayeed.

**Comment by machawk1** [comment]
Ping @ibnesayeed (CC @N0taN3rd for reference)

**Comment by N0taN3rd** [comment]
@machawk1 @ibnesayeed SO THIS IS WHERE YOU GUYS GOT THE ODU + WSDL LOGOS!!!!

**Comment by machawk1** [comment]
This is a place to catalog these, @N0taN3rd, until we can establish some branding. I ought to upload the PSD of the frog+crown. It's 72ppi (frog was bitmap) but could be useful in scenarios like your @oduwsdl gh-pages revamp. Also, that would not fulfill this ticket. Upload your logo, @ibnesayeed -- that would do it.
